apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rhads-ci
resources:
  - pvc.yaml
  - job.yaml
configMapGenerator:
  - name: rhads-maven-warm-poms
    files:
      - quarkus-agentic.xml=poms/quarkus-agentic.xml
      - quarkus-hitl.xml=poms/quarkus-hitl.xml
      - camel-agentic.xml=poms/camel-agentic.xml
      - camel-supervisor.xml=poms/camel-supervisor.xml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
