- hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/demo.yaml
  roles:
    - role: openshift-config
    - role: gitops-config
    - role: gitops-bootstrap
    - role: keycloak-config
    - role: gitops-deploy-gitlab
    - role: gitlab-config
    - role: quay-config
    - role: rhtas-config
    - role: tpa-config
    - role: acs-config
    - role: rhdh-config
    - role: dashboard
