apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quarkus-template.name" . }}-maas
  labels:
    {{- include "quarkus-template.labels" . | nindent 4 }}
type: Opaque
stringData:
  MAAS_BASE_URL: {{ .Values.maas.baseUrl | quote }}
  MAAS_MODEL: {{ .Values.maas.model | quote }}
  MAAS_API_KEY: {{ .Values.maas.apiKey | quote }}
